engines/address/config/routes.rb
Address::Engine.routes.draw do
  resources :enterprises, path: 'empreendimentos' do
    resources :enterprise_typologies, path: 'tipologias'
  end

  resources :activity_types,           path: 'atividade-tipos'
  resources :registry_types,           path: 'registro-tipos'
  resources :regions,                  path: 'regioes'
  resources :unit_use_types,           path: 'unidade-tipo-usos'
  resources :unit_situation_types,     path: 'unidade-tipo-situacoes'
  resources :unit_cadastre_situations, path: 'unidade-cadastro-situacoes'
  resources :labels,                   path: 'etiquetas'

  resources :enterprise_companies,     path: 'empresas' do
    resources :enterprise_company_users,     path: 'empresas-usuarios'
  end

  resources :units, path: 'unidades' do
    resources :bookings, path: 'reservas', only: %i[new create]
    resources :unit_activities, path: 'observacoes'
    resources :unit_labels, path: 'etiqueta'
    resources :unit_registries, path: 'registro'
    resources :unit_images, path: 'imagens'
  end

  resources :unit_details, path: 'detalhes'
  resources :offices, path: 'cartorios'

  resources :documents
end

engines/address/app/models/address/activity_type.rb
require_dependency 'support/address/activity_type'

module Address
  class ActivityType < Support::Address::ActivityType
    validates :name, uniqueness: true, presence: true
  end
end

engines/address/app/models/address/application_record.rb
module Address
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/address/app/models/address/booking.rb
require_dependency 'support/address/booking'

module Address
  class Booking < Support::Address::Booking
    validates :cpf, cpf: true, presence: true
    validates :observation, presence: true
  end
end

engines/address/app/models/address/enterprise.rb
require_dependency 'support/address/enterprise'

module Address
  class Enterprise < Support::Address::Enterprise
    has_many :enterprise_typologies

    validates :name, presence: true

    scope :by_name,    ->(name)    { where("name ILIKE ?", "%#{name}%") }
    scope :by_edital,  ->(edital)  { where(number_document: edital) }
    scope :by_process, ->(process) { where(number_assessment: process) }
    scope :by_status,  ->(status)  { where(status: status) }
    scope :by_company, ->(company) { where(company_id: company) }
  end
end

engines/address/app/models/address/enterprise_company.rb
require_dependency 'support/address/enterprise_company'

module Address
  class EnterpriseCompany < Support::Address::EnterpriseCompany

    belongs_to :city, class_name: 'Support::Common::City'
    belongs_to :state, class_name: 'Support::Common::State'

    validates :name, uniqueness: true, presence: true

    has_many :enterprise_company_users, dependent: :destroy
  end
end

engines/address/app/models/address/enterprise_company_user.rb
require_dependency "support/address/enterprise_company_user"

module Address
  class EnterpriseCompanyUser < Support::Address::EnterpriseCompanyUser
    validates :name, :email, :password, presence: true

  end
end

engines/address/app/models/address/enterprise_typology.rb
require_dependency 'support/address/enterprise_typology'
require 'bd_money/rails'

module Address
  class EnterpriseTypology < Support::Address::EnterpriseTypology
    belongs_to :enterprise, required: false

    validates :name, :unit_quantity, presence: true

    money :value_start, precision: 2
    money :value_end, precision: 2
    money :value_general, precision: 2

    def value_start=(value)
      self[:value_start] = 0 unless value.present?
      self[:value_start] = value.gsub('.','').gsub(',','.')
    end

    def value_end=(value)
      self[:value_end] = 0 unless value.present?
      self[:value_end] = value.gsub('.','').gsub(',','.')
    end

    def value_general=(value)
      self[:value_general] = 0 unless value.present?
      self[:value_general] = value.gsub('.','').gsub(',','.')
    end
  end
end

engines/address/app/models/address/label.rb
require_dependency 'support/address/label'

module Address
  class Label < Support::Address::Label
    validates :name, uniqueness: true, presence: true
  end
end

engines/address/app/models/address/region.rb
require_dependency 'support/address/region'

module Address
  class Region < Support::Address::Region
    validates :name, uniqueness: true, presence: true
  end
end

engines/address/app/models/address/registry_type.rb
require_dependency 'support/address/registry_type'

module Address
  class RegistryType < Support::Address::RegistryType
    validates :name, uniqueness: true, presence: true
  end
end

engines/address/app/models/address/unit.rb
require_dependency 'support/address/unit'

module Address
  class Unit < Support::Address::Unit
    attr_accessor :enterprise_id

    belongs_to :city, required: false, class_name: 'Support::Common::City'

    has_many :unit_activities
    has_many :unit_registries
    has_many :unit_labels
    has_many :unit_images

    scope :by_city,  ->(city) { where(city_id: city) }
    scope :by_burgh, ->(burgh) { where(burgh: burgh) }
    scope :by_group, ->(group) { where(group: group) }
    scope :by_block, ->(block) { where(block: block) }
    scope :by_unit,  ->(unit)    { where(unit: unit) }

    scope :by_situation, ->(situation) {
      where(id: Support::Address::UnitSituation.select(:unit_id).where(created_at: Support::Address::UnitSituation
                                            .select("MAX(created_at)")
                                            .group(:unit_id), situation_type_id: situation))

     }

    scope :by_registry, -> (registry) {
      where(id: Support::Address::UnitRegistry.select(:unit_id).where(created_at: Support::Address::UnitRegistry
                                            .select("MAX(created_at)")
                                            .group(:unit_id), registry_type_id: registry))

     }
  end
end

engines/address/app/models/address/unit_activity.rb
require_dependency 'support/address/unit_activity'

module Address
  class UnitActivity < Support::Address::UnitActivity

    belongs_to :user, class_name: 'Pivotal::User'
    belongs_to :actvity_type, class_name: 'Address::ActivityType'

    validates :actvity_type_id, presence: true

    mount_uploader :document, Address::DocumentUploader
  end
end

engines/address/app/models/address/unit_cadastre_situation.rb
require_dependency 'support/address/unit_cadastre_situation'

module Address
  class UnitCadastreSituation < Support::Address::UnitCadastreSituation
    validates :name, uniqueness: true, presence: true
  end
end

engines/address/app/models/address/unit_image.rb
require_dependency 'support/address/unit_image'

module Address
  class UnitImage < Support::Address::UnitImage

    validates :image, presence: true

    mount_uploader :image, Support::ImageUploader
  end
end

engines/address/app/models/address/unit_image_field.rb
require_dependency 'support/address/unit_image'

module Address
  class UnitImageField < Support::Address::UnitImage
    validates :image, presence: true

  end
end

engines/address/app/models/address/unit_label.rb
require_dependency 'support/address/unit_label'

module Address
  class UnitLabel < Support::Address::UnitLabel

    belongs_to :user, class_name: 'Pivotal::User'
    belongs_to :label, class_name: 'Address::Label'

    validates :label_id, presence: true

  end
end

engines/address/app/models/address/unit_registry.rb
require_dependency 'support/address/unit_registry'

module Address
  class UnitRegistry < Support::Address::UnitRegistry
    belongs_to :registry_type, class_name: 'Address::RegistryType'
    
    validates :registry_type_id, presence: true
  end
end

engines/address/app/models/address/unit_situation_type.rb
require_dependency 'support/address/unit_situation_type'

module Address
  class UnitSituationType < Support::Address::UnitSituationType
    validates :name, uniqueness: true, presence: true
  end
end

engines/address/app/models/address/unit_use_type.rb
require_dependency 'support/address/unit_use_type'

module Address
  class UnitUseType < Support::Address::UnitUseType
    validates :name, uniqueness: true, presence: true
  end
end

engines/address/app/controllers/address/activity_types_controller.rb
require_dependency 'address/application_controller'

module Address
  class ActivityTypesController < ApplicationController
    before_action :set_activity_types
    before_action :set_activity_type, only: %i[edit update destroy]

    def index; end

    def new
      @activity_type = Address::ActivityType.new
    end

    def create
      @activity_type = Address::ActivityType.new(set_params)
      @activity_type.save
    end

    def edit; end

    def update
      @activity_type.update(set_params)
    end

    def destroy
      @activity_type.destroy
    end

    private

    def set_params
      params.require(:activity_type).permit(:name, :status)
    end

    def set_activity_types
      @activity_types = Address::ActivityType.all
    end

    def set_activity_type
      @activity_type = Address::ActivityType.find(params[:id])
    end
  end
end

engines/address/app/views/address/unit_situation_types/_edit.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %h5.modal-title Editar tipo de situação da unidade
      %a.close
        %i.fas.fa-times
    .modal-body
      = render 'form'

engines/address/app/views/address/unit_situation_types/_form.html.haml
= simple_form_for @unit_situation_type, remote: true do |f|
  = f.input :name, placeholder: 'Digite um nome'
  = f.input :description, placeholder: 'Digite uma descrição'
  = f.input :status, as: :select, include_blank: 'selecione...'
  = f.button :submit, class: 'btn btn-success'

engines/address/app/views/address/unit_situation_types/_index.html.haml
.card
  .card-body.card-header.border-left-yellow
    .card-title
      Listando (#{@unit_situation_types.count}) registro(s)
      .float-right.group-action
        = link_to "Excel", "#", class: 'btn btn-secondary btn-sm'
        = link_to "Imprimir", "#", class: 'btn btn-secondary btn-sm'

  .card-body
    %table.table.table-bordered.table-striped.table-celled
      %thead
        %tr
          %th Nº
          %th Nome
          %th Descrição
          %th Status
          %th
      %tbody
        - if @unit_situation_types.present?
          -@unit_situation_types.each do |unit_situation_type|
            %tr{class: "row-type-#{unit_situation_type.id}"}
              %td.collapsing= unit_situation_type.id
              %td= unit_situation_type.name
              %td= unit_situation_type.description
              %td.collapsing= unit_situation_type.status.status_format
              %td.collapsing
                .dropdown
                  %button.btn.btn-success.btn-icon.btn-sm.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                    %i.fa.fa-cog
                    %i.ti-angle-down
                  .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenuButton"}
                    = link_to "Editar", edit_unit_situation_type_path(unit_situation_type), class: 'dropdown-item', remote: true
                    = link_to "Excluir", unit_situation_type_path(unit_situation_type), method: :delete, class: 'dropdown-item', data: {confirm: t(:confirm)}, remote: true
        - else
          %tr
            %td{colspan: 6}
              %i Nenhum registro encontrado.

engines/address/app/views/address/unit_situation_types/_index_sidebar.html.haml
#sidebar
  .card
    .card-body.card-header.border-left-yellow
      .card-title
        Operações
        = link_to "javascript:void(0)", class: "collapsing-link" do
          %i.fa.fa-minus
    .card-body.card-list
      = link_to "Adicionar tipo de situação da unidade", new_unit_situation_type_path, class: 'filter-nav-item', remote: true
      %hr.divider
      = link_to "Gestão de tipos de atividade", activity_types_path, class: 'filter-nav-item'
      = link_to "Gestão de tipos de registro", registry_types_path, class: 'filter-nav-item'
      = link_to "Gestão de regiões", registry_types_path, class: 'filter-nav-item'
      = link_to "Gestão de tipos de uso da unidade", unit_use_types_path, class: 'filter-nav-item'

engines/address/app/views/address/unit_situation_types/_new.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %h5.modal-title Adicionar tipo de situação da unidade
      %a.close
        %i.fas.fa-times
    .modal-body
      = render 'form'

engines/address/app/views/address/unit_situation_types/_save.js.haml
- if @unit_situation_type.errors.any?
  $("#modal").html("#{escape_javascript(render 'new')}");
  update_js();
- else
  $(".index-content").html("#{escape_javascript(render 'index')}");
  $(".row-type-#{@unit_situation_type.id}").addClass('table-success');
  $("#modal").html("#{escape_javascript(render 'layouts/partials/modal_success')}");

  update_js();

engines/address/app/views/address/unit_situation_types/index.html.haml
.fluid-container
  .row.mt-4
    .col-md-12
      .card#header.border-left-yellow
        .card-body
          .title Imóveis
          .subtitle Tipo de situação da unidade
  .row.mt-4
    .col-md-2.index-sidebar
      = render 'index_sidebar'
    .col-md-10.index-content
      = render 'index'